# Generated by Django 4.0.4 on 2022-04-28 07:16

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='feature_display',
            field=models.TextField(blank=True, choices=[('card', 'Cards'), ('list', 'List')], help_text='Layout style for featured content.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_limit',
            field=models.IntegerField(default=4, help_text='Max number of featured pages to display.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a size'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7')], required=False))])), ('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(required=True))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.core.blocks.CharBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('attribution', wagtail.core.blocks.TextBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('attribution', wagtail.core.blocks.TextBlock(required=True)), ('citation_text', wagtail.core.blocks.TextBlock(required=False)), ('citation_link', wagtail.core.blocks.URLBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='view', template='blocks/embed_block.html'))], blank=True, verbose_name='Page content blocks.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='feature_pages',
            field=wagtail.core.fields.StreamField([('page', wagtail.core.blocks.PageChooserBlock())], blank=True, null=True, verbose_name='Featured pages.'),
        ),
    ]
