# Generated by Django 4.0.4 on 2022-05-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
