# Generated by Django 4.0.4 on 2022-05-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_alter_flexpage_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FlexPage',
        ),
    ]
