# Generated by Django 4.0.4 on 2022-05-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_alter_formpage_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='formpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormPage',
        ),
    ]
