# Generated by Django 4.0.4 on 2022-05-05 06:46

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='abstract',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Summary of the page used by cards.'),
        ),
    ]
