# Generated by Django 4.0.4 on 2022-05-16 03:34

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtailmath.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='page_content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a size'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7')], required=False))])), ('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'image', 'code', 'blockquote'], required=True))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.core.blocks.TextBlock(required=True)), ('caption', wagtail.core.blocks.TextBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(required=True)), ('citation_text', wagtail.core.blocks.CharBlock(required=False)), ('citation_link', wagtail.core.blocks.URLBlock(required=False))])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('python', 'Python'), ('sql', 'SQL'), ('yaml', 'YAML'), ('arduino', 'Arduino'), ('autohotkey', 'AutoHotkey'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('diff', 'Diff'), ('django', 'Django/Jinja2'), ('java', 'Java'), ('javadoc', 'JavaDoc'), ('latex', 'LaTeX'), ('less', 'Less'), ('lua', 'Lua'), ('makefile', 'Makefile'), ('markdown', 'Markdown'), ('matlab', 'MATLAB'), ('nginx', 'nginx'), ('pascal', 'Pascal + Object Pascal'), ('php', 'PHP'), ('phpdoc', 'PHPDoc'), ('r', 'R'), ('regex', 'Regex'), ('rest', 'reST (reStructuredText)'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sas', 'SAS'), ('sass', 'Sass (Sass)'), ('scss', 'Sass (Scss)'), ('tcl', 'Tcl'), ('typescript', 'TypeScript'), ('vim', 'vim'), ('wiki', 'Wiki markup')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))])), ('equation', wagtailmath.blocks.MathBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='view', template='blocks/default_block.html'))], blank=True, verbose_name='Page content blocks.'),
        ),
        migrations.AlterField(
            model_name='formpage',
            name='content',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=True)), ('size', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('', 'Select a size'), ('h2', 'h2'), ('h3', 'h3'), ('h4', 'h4'), ('h5', 'h5'), ('h6', 'h6'), ('h7', 'h7')], required=False))])), ('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'image', 'code', 'blockquote'], required=True))])), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('alt_text', wagtail.core.blocks.TextBlock(required=True)), ('caption', wagtail.core.blocks.TextBlock(required=False)), ('attribution', wagtail.core.blocks.CharBlock(required=False))])), ('quote', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.TextBlock(required=True)), ('attribution', wagtail.core.blocks.CharBlock(required=True)), ('citation_text', wagtail.core.blocks.CharBlock(required=False)), ('citation_link', wagtail.core.blocks.URLBlock(required=False))])), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('css', 'CSS'), ('html', 'HTML'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('python', 'Python'), ('sql', 'SQL'), ('yaml', 'YAML'), ('arduino', 'Arduino'), ('autohotkey', 'AutoHotkey'), ('c', 'C'), ('csharp', 'C#'), ('cpp', 'C++'), ('diff', 'Diff'), ('django', 'Django/Jinja2'), ('java', 'Java'), ('javadoc', 'JavaDoc'), ('latex', 'LaTeX'), ('less', 'Less'), ('lua', 'Lua'), ('makefile', 'Makefile'), ('markdown', 'Markdown'), ('matlab', 'MATLAB'), ('nginx', 'nginx'), ('pascal', 'Pascal + Object Pascal'), ('php', 'PHP'), ('phpdoc', 'PHPDoc'), ('r', 'R'), ('regex', 'Regex'), ('rest', 'reST (reStructuredText)'), ('ruby', 'Ruby'), ('rust', 'Rust'), ('sas', 'SAS'), ('sass', 'Sass (Sass)'), ('scss', 'Sass (Scss)'), ('tcl', 'Tcl'), ('typescript', 'TypeScript'), ('vim', 'vim'), ('wiki', 'Wiki markup')], help_text='Coding language', identifier='language', label='Language')), ('code', wagtail.core.blocks.TextBlock(identifier='code', label='Code'))])), ('equation', wagtailmath.blocks.MathBlock()), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='view', template='blocks/default_block.html'))], blank=True, verbose_name='Page content blocks.'),
        ),
    ]
