# Generated by Django 4.0.3 on 2022-04-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(blank=True, help_text='Main text displayed in the hero section.', max_length=120)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Subtitle following the main title in the hero section.', max_length=200)),
                ('action_button_text', models.CharField(blank=True, default='Learn More', help_text='Action button text.', max_length=20)),
                ('action_button_link', models.ForeignKey(blank=True, help_text='Internal page link when button is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
