# Generated by Django 4.0.3 on 2022-04-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='action_button_link',
            field=models.ForeignKey(blank=True, help_text='Internal page link when button is clicked.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='action_button_text',
            field=models.CharField(blank=True, default='Learn More', help_text='Action button text.', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True, help_text='Subtitle following the main title in the hero section.', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main text displayed in the hero section.', max_length=120),
        ),
    ]
