# Generated by Django 4.0.3 on 2022-04-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='postpageblogcategory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='blog_category',
        ),
        migrations.RemoveField(
            model_name='postpageblogcategory',
            name='page',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
