# Generated by Django 4.0.3 on 2022-04-10 07:45

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postgalleryimage_and_more'),
        ('categories', '0001_initial'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='categories.category'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='content',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.RichTextBlock())])), ('image_paragraph', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True),
        ),
        migrations.AddField(
            model_name='postpage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='PostPageBlogCategory',
        ),
        migrations.AddField(
            model_name='postgalleryimage',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='postgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='blog.postpage'),
        ),
    ]
